### ISSUE TITLE
Thoughts on Class variable for default truncation

### ISSUE THREAD

**Issue by n-at-han-k** [readysteady/percentage#8]
Adding `.truncate(2)` after every call to `Percentage.new` when displaying the information in a table is rather tedious.

What are your thoughts on having an option to set truncation for future calls?
Something like the following would be nice and easy to implement.

```ruby
Percentage.default_truncation = 2
Percentage.new(Rational(1,3)).to_s
# => 0.33%
```

When working with rails you could then create an initialiser `app/config/initializers/percentage.rb` to set this globally.
```ruby
# app/config/initializers/percentage.rb
Percentage.default_truncation = 2
```

**Comment by timcraft** [comment]
I don't think having global options/config is appropriate for this gem.

If you want to standardise on the number of digits throughout your application you can use a helper. For example:

```erb
<%= percentage_format @change %>
```

That's the exact same approach as if you were using another numeric class like BigDecimal or Rational, or some other datatype where you need more than the implicit #to_s can provide (date, time, money etc).

You can also use the Rails helper, although it's more verbose:

```erb
<%= number_to_percentage(@change.to_d, precision: 1) %>
```

Another alternative when you're generating tables would be to use some kind of table abstraction that can format values based on their type.

**Comment by n-at-han-k** [comment]
Good idea, I like it.
